### PR TITLE
Changed key layout to be more 'natural' and to ones that seem to make…

### PR DESCRIPTION
**Pull request by ghost**
… more sense.

### CODE REVIEW

**Comment by ghost** [comment]
Keys:

B - Backup Save
A - Restore Save
X - Erase Save
Y - Restart
START - Exit

**Comment by TuxSH** [comment]
Using A and B causes a conflict when choosing whether to overwrite a save file or not and when choosing whether to erase save data or not.

**Comment by ghost** [comment]
That's odd, since it works fine for me... Maybe I should add a slight delay after the key press, to help prevent the problem.

**Comment by TuxSH** [comment]
Maybe ...
But if the end-user hold either A or B he could be screwed.

And -- this is my opinion -- the key used to erase a save file shouldn't be near the other ones.

**Comment by ghost** [comment]
True. Perhaps when the user is promped to confirm or cancel, they have to press Up for confirm and down for cancel.

This way, they cannot accidentally do anything :)

**Comment by TuxSH** [comment]
But there A and B are the most conventional keys to use.

**Comment by ihaveamac** [comment]
I think when something that could accidentally erase something the user doesn't want to erase, it should have a special key for it to prevent any accidental actions.

**Comment by ghost** [comment]
I guess. So are the L and R keys the most common to break, that's why I was hoping to purge the idea of using them.

SysUpdater doesn't use conventional keys and neither does TinyFormat. They don't use conventional keys as it ensures the user was paying attention to what they are clicking, instead of using the common A and B.

In my opinion, having them as A and B makes it easier to mess up something, due to the common "force of habit".

I guess that's just my way of thinking :P Anyways, I compiled the latest source and it only makes a CIA and SMDH, no 3DSX 0~0

**Comment by ghost** [comment]
@ihaveamac agreed

**Comment by ghost** [comment]
Changed A and B to confirm and cancel, to UP and DOWN.

**Comment by TuxSH** [comment]
Delete cmake-generated files then reconfigure with -DCIA=OFF

**Comment by ghost** [comment]
@TuxSH  Okey. Thanks :D

**Comment by TuxSH** [comment]
I'll see if I can implement user settings when I have time.

**Comment by ghost** [comment]
Okey doke. I wonder if @AlbertoSONIC is able to contribute to this. He's the dude who made the GUI system for rxTools.

**Comment by TuxSH** [comment]
I don't know anything about how to make a GUI for a 3DS homebrew, or graphical stuff in general. x)

**Comment by ghost** [comment]
Me neither, but @AlbertoSONIC does :D The question is will he be interested in adding it or not.

**Comment by AlbertoSONIC** [comment]
I can work on it.. But won't take a look at this until tomorrow afternoon (I have a test tomorrow morning :-1:  )

**Comment by ghost** [comment]
Yay Alberto :D (Darn. 2 weeks ago, I passed out in my English assessment xD Whoops)

**Comment by ghost** [comment]
@AlbertoSONIC Maybe the UI could look like the NDS ver: https://gbatemp.net/screenshots/%5B2719%5Dndsbackuptool.jpg  or maybe even Material Design themed. Just a suggestion tho. Not my project xP

**Comment by AlbertoSONIC** [comment]
@lavanoid First i need to get this project to compile xD... cmake is such a pain!

**Comment by ghost** [comment]
@AlbertoSONIC Ubuntu FTW XD Wanna use my VPS, to do it?

**Comment by AlbertoSONIC** [comment]
No no I need to do this on my laptop! I guess I'll try to fix it this afternoon...

**Comment by ghost** [comment]
Okey dokey. Otherwise I would have suggested building on that, then transfer it to the laptop via filezilla. That was just an idea if you couldn't get it working.

If you're using Linux for your compiling, I could help you out with configuring it all, if you want.

**Comment by AlbertoSONIC** [comment]
Unfortunately I'm using windows 10.. I'm having some path issues...

**Comment by ghost** [comment]
Oh. My philosophy: If it's Windows 10, the problem is Windows itself xD (Not entirely true but I just don't like 10, lol)

Welp, can't help much there as I always build stuff on Linux 0~0 If you haven't managed to get it working later this evening, I'll see if I can get it building on my Windows installation and help you out with it, though I'm sure you'll manage it yourself :P

**Comment by AlbertoSONIC** [comment]
I get this:

> [ 57%] Built target TWLSaveTool
> [ 71%] Generating TWLSaveTool.smdh
> [ 85%] Generating TWLSaveTool.bnr
> make[2]: BANNERTOOL-NOTFOUND: Command not found
> make[2]: **\* [TWLSaveTool.bnr] Error 127
> make[1]: **\* [CMakeFiles/TWLSaveTool_cia.dir/all] Error 2
> make: **\* [all] Error 2

But bannertool is inside both DevKitPro/msys/bin and DevKitPro/DevKitArm/bin and added to path!

EDIT: And If I just type "bannertool" in cmd window, it says

> Usage: bannertool <command> <args>
> Available commands:
> makebanner - Creates a .bnr file.
>   -i/--image: PNG file to use as the banner's image. Interchangeable with -ci.
>   -a/--audio: WAV file to use as the banner's tune. Interchangeable with -ca.
>   -ci/--cgfximage: CGFX file to use as the banner's image. Interchangeable with -i.
>   -ca/--cwavaudio: CWAV file to use as the banner's tune. Interchangeable with -a.
>   -o/--output: File to output the created banner to.
> makesmdh - Creates a .smdh/.icn file.
>   -s/--shorttitle: Short title of the application.
>   -l/--longtitle: Long title of the application.
>   -p/--publisher: Publisher of the application.
>   -i/--icon: PNG file to use as an icon.
>   -o/--output: File to output the created SMDH/ICN to.
>   -r/--regions: Optional. Comma separated list of regions to lock the SMDH to.
>      Valid regions: regionfree, japan, northamerica, europe, australia, china, korea, taiwan.
>   -f/--flags: Optional. Flags to apply to the SMDH file.
>      Valid flags: visible, autoboot, allow3d, requireeula, autosave, extendedbanner, ratingrequired, savedata, recordusage, nosavebackups.
>   -mmid/--matchmakerid: Optional. Match maker ID of the SMDH.
>   -ev/--eulaversion: Optional. Version of the EULA required to be accepted before launching.
>   -obf/--optimalbannerframe: Optional. Optimal frame of the accompanying banner.
>   -spid/--streetpassid: Optional. Streetpass ID of the SMDH.
> makecwav - Creates a CWAV file from a WAV.
>   -i/--input: WAV file to convert.
>   -o/--output: File to output the created CWAV to.
> lz11 - Compresses a file with LZ11.
>   -i/--input: File to compress.
>   -o/--output: File to output the compressed data to.

So it works!

**Comment by ghost** [comment]
I'd laugh if it worked if you renamed bannertool to "BANNERTOOL-NOTFOUND.exe". Tried putting bannertool in C:\Windows, maybe? I'll look when I get home.

**Comment by ghost** [comment]
Means that the buildscript is dodgy 0~0

**Comment by AlbertoSONIC** [comment]
Wtf actually renaming bannertool to BANNERTOOL-NOTFOUND.exe fixed it! xD

Same for makerom!

**Comment by ghost** [comment]
Wow xD I wasn't expecting that to work.

**Comment by TuxSH** [comment]
See 0bf5047b7e5edafe6fb257f6c1eb7931559051a3. Compiling should be way easier

**Comment by TuxSH** [comment]
In addition to FSUSER_GetLegacyRomHeader, access control flag "TwlCardBackup" (which we're using) grants access to **FSUSER_GetLegacyBannerData** as well, something that's really relevant for a GUI  :p

**Comment by ghost** [comment]
I wish I understood what that means exactly but sounds awesome! :D

**Comment by TuxSH** [comment]
This means that we're able to read the cartridge icon data, documented [here](http://problemkaputt.de/gbatek.htm#dscartridgeicontitle)

**Comment by ghost** [comment]
Oh wow! Now that's awesome! :D Gonna be great when/if we get the GUI implemented.

**Pull request merged**
